### ISSUE TITLE
/root/influx-bitmex/index.ts:2 import { InfluxDB, Point, HttpError, WritePrecision } from '@influxdata/influxdb-client';

### ISSUE THREAD

**Issue by Pat2018-1** [temp3l/influx-bitmex#1]
Hi,

Thanks a lot for your hard work but i cant get the program working?
get this fault: /root/influx-bitmex/index.ts:2
import { InfluxDB, Point, HttpError, WritePrecision } from '@influxdata/influxdb-client';

Regards,
Patrick

**Comment by temp3l** [comment]
I added the missing dependencies and a startscript, run:

```
npm install
npm run start
```
or


```
yarn
yarn start
```

**Comment by temp3l** [comment]
have fun
