### ISSUE TITLE
Install Tutorial.

### ISSUE THREAD

**Issue by ingnelson** [temp3l/influx-bitmex#2]
Hello sir.
I would like tp use this program , can you create a mini tutorial , please. i am just a trader , i do not know much about programing.

i just sign up InfluxDB. 

one more question : this can work on localhost on windows using PowerShell Terminal or just on InfluxDB ? 

I hope you answer for the mini tutorial to install and run this project, please

**Comment by temp3l** [comment]
hi,
yes should work on windoze (except the beep-sound)

I've added a few notes regarding the influxdb setup and installation

make sure u have a working influx running http://localhost:9999/

**Comment by temp3l** [comment]
have fun
